// data properties
export const CRUD_DATA_PROPERTIES_INJECTION = 'crudDataPropertiesInjection'
export const CRUD_DATA_PROPERTIES = 'crudDataProperties'

// 查询
export const CRUD_SEARCH_INJECTION_FORM_MODEL = 'crudSearchInjectionFormModel'
export const CRUD_SEARCH_INJECTION_FORM_RULE = 'crudSearchInjectionFormRule'
export const CRUD_SEARCH_FORM = 'crudSearchForm'
export const CRUD_SEARCH_USE_FORM = 'crudSearchUseForm'
export const CRUD_SEARCH_INJECTION_QUERY_ATTACH_PARAMS = 'crudInjectionSearchQueryAttachParams'
export const CRUD_SEARCH_QUERY_ATTACH_PARAMS = 'crudSearchQueryAttachParams'
export const CRUD_HOOK_FUNCTION_SEARCH_RESPONSE_BEFORE = 'crudHookFunctionSearchResponseBefore'
export const CRUD_HOOK_FUNCTION_SEARCH_RESPONSE = 'crudHookFunctionSearchResponse'
export const CRUD_HOOK_FUNCTION_SEARCH_RESPONSE_SUCCESS_BEFORE = 'crudHookFunctionSearchResponseSuccessBefore'
export const CRUD_HOOK_FUNCTION_SEARCH_RESPONSE_SUCCESS = 'crudHookSearchResponseSuccess'
export const CRUD_HOOK_FUNCTION_SEARCH_RESPONSE_SUCCESS_AFTER = 'crudHookSearchResponseSuccessAfter'
export const CRUD_HOOK_FUNCTION_SEARCH_RESPONSE_ERROR = 'crudHookSearchResponseError'
export const CRUD_HOOK_FUNCTION_SEARCH_RESPONSE_FINALLY = 'crudHookSearchResponseFinally'
// 查询相关
export const CRUD_SEARCH_LOADING = 'crudSearchLoading'
export const CRUD_SEARCH_DATA = 'crudSearchData'
// 查询分页相关
export const CRUD_INJECTION_SEARCH_PAGING_INIT = 'crudInjectionSearchPagingInit'
export const CRUD_SEARCH_PAGING_PAGE_NUM = 'curdSearchPagingPageNum'
export const CRUD_SEARCH_PAGING_PAGE_SIZE = 'curdSearchPagingPageSize'
export const CRUD_SEARCH_PAGING_TOTAL = 'crudSearchPagingTotal'

// crud 表单
export const CRUD_INJECTION_FORM_MODEL = 'crudInjectionFormModel'
export const CRUD_INJECTION_FORM_RULE = 'crudInjectionFormRule'
export const CRUD_FORM = 'crudForm'
export const CRUD_FORM_USE_FORM = 'crudFormUseForm'
export const CRUD_FORM_TYPE = 'crudFormType'
export const CRUD_FORM_TYPE_ADD = 'crudFormTypeAdd'
export const CRUD_FORM_TYPE_MODIFY = 'crudFormTypeModify'
export const CRUD_FORM_VISIBLE = 'crudFormVisible'
export const CRUD_FORM_LOADING = 'crudFormLoading'
export const CRUD_HOOK_FUNCTION_SEARCH_ONE_RESPONSE_BEFORE = 'crudHookSearchOneResponseBefore'
export const CRUD_HOOK_FUNCTION_SEARCH_ONE_RESPONSE = 'crudHookSearchOneResponse'
export const CRUD_HOOK_FUNCTION_SEARCH_ONE_RESPONSE_SUCCESS_BEFORE = 'crudHookSearchOneResponseSuccessBefore'
export const CRUD_HOOK_FUNCTION_SEARCH_ONE_RESPONSE_SUCCESS = 'crudHookSearchOneResponseSuccess'
export const CRUD_HOOK_FUNCTION_SEARCH_ONE_RESPONSE_SUCCESS_AFTER = 'crudHookSearchOneResponseSuccessAfter'
export const CRUD_HOOK_FUNCTION_SEARCH_ONE_RESPONSE_ERROR = 'crudHookSearchOneResponseError'
export const CRUD_HOOK_FUNCTION_SEARCH_ONE_RESPONSE_FINALLY = 'crudHookSearchOneResponseFinally'
// add / modify / delete
export const CRUD_SAVE_BUTTON_LOADING = 'crudSaveButtonLoading'
export const CRUD_HOOK_FUNCTION_FORM_SAVE_BEFORE = 'crudHookFormSaveBefore'
export const CRUD_HOOK_FUNCTION_FORM_SAVE = 'crudHookFormSave'
export const CRUD_HOOK_FUNCTION_FORM_SAVE_SUCCESS_BEFORE = 'crudHookFormSaveSuccessBefore'
export const CRUD_HOOK_FUNCTION_FORM_SAVE_SUCCESS = 'crudHookFormSaveSuccess'
export const CRUD_HOOK_FUNCTION_FORM_SAVE_SUCCESS_AFTER = 'crudHookFormSaveSuccessAfter'
export const CRUD_HOOK_FUNCTION_FORM_SAVE_ERROR = 'crudHookFormSaveError'
export const CRUD_HOOK_FUNCTION_FORM_SAVE_FINALLY = 'crudHookFormSaveFinally'
export const CRUD_HOOK_FUNCTION_FORM_DELETE_BEFORE = 'crudHookFormDeleteBefore'
export const CRUD_HOOK_FUNCTION_FORM_DELETE = 'crudHookFormDelete'
export const CRUD_HOOK_FUNCTION_FORM_DELETE_SUCCESS_BEFORE = 'crudHookFormDeleteSuccessBefore'
export const CRUD_HOOK_FUNCTION_FORM_DELETE_SUCCESS = 'crudHookFormDeleteSuccess'
export const CRUD_HOOK_FUNCTION_FORM_DELETE_SUCCESS_AFTER = 'crudHookFormDeleteSuccessAfter'
export const CRUD_HOOK_FUNCTION_FORM_DELETE_ERROR = 'crudHookFormDeleteError'
export const CRUD_HOOK_FUNCTION_FORM_DELETE_FINALLY = 'crudHookFormDeleteFinally'
export const CRUD_FORM_DELETE_LOADING = 'crudFormDeleteLoading'

// other
export const CRUD_INJECTION_SEARCH_READY_BEFORE_PROMISE = 'crudInjectionSearchReadyBeforePromise'

// api
export const CRUD_API_QUERY = 'crudApiQuery'
export const CRUD_API_QUERY_ONE = 'crudApiQueryOne'
export const CRUD_API_ADD = 'crudApiAdd'
export const CRUD_API_MODIFY = 'crudApiModify'
export const CRUD_API_DELETE = 'curdApiDelete'

// function
export const CRUD_FUNCTION_QUERY = 'crudFunctionQuery'
export const CRUD_FUNCTION_QUERY_AFTER_CHANGE_PAGE = 'crudFunctionQueryAfterChangePage'
export const CRUD_FUNCTION_OPEN_FORM_ADD = 'crudFunctionOpenFormAdd'
export const CRUD_FUNCTION_OPEN_FORM_MODIFY = 'crudFunctionOpenFormModify'
export const CRUD_FUNCTION_SAVE = 'crudFunctionSave'
export const CRUD_FUNCTION_DELETE = 'crudFunctionDelete'
